plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ardal.operations'
    compileSdk 35

    signingConfigs {
        ardalInternal {
            storeFile file('../ardal-internal.keystore')
            storePassword 'ardal-internal-2026'
            keyAlias 'ardalinternal'
            keyPassword 'ardal-internal-2026'
        }
    }

    defaultConfig {
        applicationId 'com.ardal.operations.nativeocr'
        minSdk 23
        targetSdk 35
        versionCode 9
        versionName '0.8.2'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.ardalInternal
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.ardalInternal
        }
    }
}

dependencies {\n    implementation 'androidx.core:core:1.13.1'
    implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
