plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ardal.operations'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ardal.operations'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.7.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
}
